### ISSUE TITLE
Чекбоксы

### ISSUE THREAD

**Issue by sfcl** [sfcl/severcart#100]
День добрый,
Есть ли возможность отключить по-умолчанию чекбокс(ы) возврата картриджей при передаче картриджа пользователю ?
Смысл в том что у нас в организации много пользователей, но нет желания заводить их всех по отдельности, даже по если по кабинетам. Проще завести одну сущность на всех, к примеру "Конечный пользователь". Следовательно из этого все картриджи будут передаваться одному пользователю. А ваша система каждый раз будет включать все галочки на уже переданные картриджи предлагая их вернуть.
Каждый раз кликать их будет не очень удобно, вопрос в том как сделать их отключенными по умолчанию ?

**Comment by sem174** [comment]
_ venv\severcart\index\templates\index\get_cart_ou.html
строка 15
`<td><input type="checkbox" name="take" value="{{ elem.pk }}" checked="checked" /></td>`
если заменить на
`<td><input type="checkbox" name="take" value="{{ elem.pk }}"/></td>`
чекбоксы будут по умолчанию не выбраны.
Скажите данная правка не повлияет на работу системы в целом ещё где то ?

**Comment by sfcl** [comment]
![checkbox](https://cloud.githubusercontent.com/assets/10692470/19310043/9e7c9d8c-90a1-11e6-8d5d-6d3fff4502e2.png)

Предлагаю так реализовать.

**Comment by sfcl** [comment]
Напротив заголовка "Забрать?" появится пимпочка, которая будет либо выбирать все элементы, либо отменять все.

**Comment by sem174** [comment]
А почему бы и Да )
Удобная реализация, либо выбрал все, либо выключил все.
Главное для себя я нашел как выключить по умолчанию. В той реализации как мне хочется использовать у себя в организации, в самый раз. А вот уже остальным пользователям несомненно будет удобнее включать или выключать все одной кнопкой.
