### ISSUE TITLE
Обновление под Windows

### ISSUE THREAD

**Issue by sem174** [sfcl/severcart#102]
Есть инструкция по обновлению программы под Ubuntu
http://wiki.severcart.org/doku.php/%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B_%D0%B2_ubuntu
А как обновляться под Windows ? Подходят ли шаги обновления от Ubuntu под Windows ?
Поделитесь пожалуйста информацией как правильно обновлять систему под Windows.

**Comment by sfcl** [comment]
Есть размышления по поводу вообще от отказа поддержки Windows. Потому что в будущем будет на ровне с web мордой к базе, пристыковываться самостоятельный unix daemon. Поддержка 2х платформ будет очень сложной и дорогой.

**Comment by sem174** [comment]
Ну а если тогда перефразировать мой вопрос. Если я хочу обновить последний официальный релиз на master с git ? Какие мои действия, только замена файлов или же надо делать миграцию ?

**Comment by sfcl** [comment]
Обновить можно подменив все файлы в каталоге ./venv/severcart/* на новые, но при этом сделав резервную копию ./conf/settings.py и ./conf/secure.json. После обновления возвращаем старые файлы обратно.

Далее открываем командную строку Windows cmd, в ней пишем
`
cd c:\venv\scripts\
activate.bat

cd c:/venv/severcart/
python  manage.py makemigrations
python manage.py migrate
`

Далее перезагружаем Apache. На этом обновление завершено.

**Comment by sem174** [comment]
Благодарю Вас.

**Comment by sfcl** [comment]
Опубликована инструкция http://wiki.severcart.org/doku.php/обновление_программы_в_windows
