### ISSUE TITLE
Обновление до master в Ubuntu 

### ISSUE THREAD

**Issue by sem174** [sfcl/severcart#105]
День добрый,
Поставил систему учёта под ubuntu server x86. Перенёс рабочую базу данных из под Windows на Ubuntu - работает!
Решил попробовать обновиться до версии master. Уж больно интересные комиты по исправлению ошибок. Попытался выполнить обновление по инструкции - [http://wiki.severcart.org/doku.php/%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B_%D0%B2_ubuntu](url)
**python3 manage.py makemigrations** сразу же вылезли ошибки о том что отсутствует pytz, поставил его.
**python3 manage.py migrate** - ругается на то что нет привилегий для пользователя root. Тут как я понял идёт работа с базой данных, а ней права доступа только от postgres.
Переключился на пользователя postgres, активировал от него виртуальное окружение. Но тут выскочили ошибки прав на файлы, решил временным назначением с рекурсией 777. 
В итоге команда python3 manage.py migrate отработала без ошибок.
Запустил apache, но сервер упорно выдает 500 ошибку, но что-то не могу ничего найти в логах веб сервера.
Подскажите что я сделал неправильно ?

**Comment by sem174** [comment]
поставил права 777 на файл /var/venv/severcart/logs/debug.log
После попытки зайти на страницу severcart получаю вот такой вывод:
`Page not found (404)
Request Method:	GET
Request URL:	http://vs-severcart/manage_users/login
Using the URLconf defined in conf.urls, Django tried these URL patterns, in this order:
^$ [name='dashboard']
^api/
^stock/ [name='stock']
^add_name/ [name='add_name']
^add_items/ [name='add_items']
^add_cartridge_from_barcode_scanner/ [name='add_cartridge_from_barcode_scanner']
^add_empty_cartridge_from_barcode_scanner/ [name='add_empty_cartridge_from_barcode_scanner']
^add_empty_cartridge/ [name='add_empty_cartridge']
^tree_list/ [name='tree_list']
^add_type/ [name='add_type']
^transfe_for_use/ [name='transfe_for_use']
^transfer_to_firm/ [name='transfer_to_firm']
^transfer_to_firm_with_scanner/ [name='transfer_to_firm_with_scanner']
^at_work/ [name='at_work']
^use/ [name='use']
^empty/ [name='empty']
^toner_refill/ [name='toner_refill']
^add_firm/ [name='add_firm']
^edit_firm/ [name='edit_firm']
^bad_browser/ [name='bad_browser']
^basket/ [name='basket']
^edit_cartridge_comment/ [name='edit_cartridge_comment']
^from_firm_to_stock/ [name='from_firm_to_stock']
^from_firm_to_stock_with_barcode/ [name='from_firm_to_stock_with_barcode']
^evaluate_service/ [name='evaluate_service']
^events/
^docs/
^reports/
^service/
^auth/
^search/
^storages/
^dhtml/
^robots\.txt
^favicon\.ico
The current URL, manage_users/login, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
`

а в файле /var/venv/severcart/logs/debug.log вот появились вот эти строки:
`WARNING 2016-10-18 13:20:29,801 [/var/venv/lib/python3.5/site-packages/django/core/handlers/base.py:182] Not Found: /manage_users/login`

**Comment by sem174** [comment]
Далее теперь вот так отображается

`OperationalError at /auth/login/
FATAL:  role "www-data" does not exist
Request Method:	POST
Request URL:	http://vs-severcart/auth/login/?next=/
Django Version:	1.9
Exception Type:	OperationalError
Exception Value:	
FATAL:  role "www-data" does not exist
Exception Location:	/var/venv/lib/python3.5/site-packages/psycopg2/__init__.py in connect, line 164
Python Executable:	/usr/bin/python3
Python Version:	3.5.2
Python Path:	
['/var/venv/lib/python3.5/site-packages',
 '/var/venv/bin',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-i386-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/severcart/conf',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts',
 '/var/venv/Lib/site-packages',
 '/var/venv/severcart',
 '/var/venv/severcart/conf',
 '/var/venv/Scripts']
Server time:	Вт, 18 Окт 2016 13:29:31 +0100`

**Comment by sfcl** [comment]
Складывается впечатление, что не установился владелец файлов www-data
chown -R www-data:www-data /var/venv/severcart/

Предлагаю заново установить с нуля на Ubuntu добившись работоспособного резульатат, после установки произвести замену базы данных, также следует иметь в виду, что по-умолчанию владельцем БД severcart является scuser.

**Comment by sem174** [comment]
Если я правильно Вас понял мне необходимо сделать так:
1. Скачать последний master
2. Установить его как новую установку по инструкциям
3. Если установка будет успешна, попробовать накатить на базу данных дамп от рабочего сервера.
Что ж попробуем.

**Comment by sfcl** [comment]
Нужно произвести переключение с dev на prod конфигурацию перед запуском install.py. Делается через ./conf/settings.py
from settings_dev import * 
подменяется на
from settings_prod import * 

Также перед запуском install.py предполагается наличие БД severcart, user: scuser, password: 123456.

**Comment by sem174** [comment]
И так раз уже начал обсуждение то напишу сразу всё.
Почистил систему от пакетов, удалил пользователя и бд из postgree сервера.
На начало установки в системе есть только webmin и апач установленный инструкции для ubuntu

`root@severcart-linux:/home/olegas# apt-get build-dep python3-lxml libpq-dev python-dev
Чтение списков пакетов… Готово
E: Вы должны заполнить sources.list, поместив туда URI источников пакетов`

Хм, вот такой вопрос а что за пакеты он просит ? Я так понимаю ему нужны некоторые ссылки на исходники, если вы их используете - поделитесь пожалуйста.

`(venv) root@severcart-linux:/var/venv# python3 /var/venv/severcart/tkinstaller/install.py
Enter the language code [en|ru]: ru
-------------------------------------------------
--------Установка пакетов зависимостей-----------
-------------------------------------------------
Установка пакетов зависимостей для Linux
10%
  Could not find a version that satisfies the requirement lxml==3.5.2 (from versions: 0.9, 0.9.1, 0.9.2, 1.0b0, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1a0, 1.1b0, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.3b0, 1.3, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 2.0a1, 2.0a2, 2.0a3, 2.0a4, 2.0a5, 2.0a6, 2.0b1, 2.0b2, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.1a1, 2.1b1, 2.1b2, 2.1b3, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2a1, 2.2b1, 2.2b2, 2.2b3, 2.2b4, 2.2, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.3b1, 2.3, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 3.0, 3.0.1, 3.0.2, 3.1b1, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0b1, 3.3.0b2, 3.3.0b3, 3.3.0b4, 3.3.0b5, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5.0b1, 3.5.0, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4)
No matching distribution found for lxml==3.5.2
Для выхода нажмите любую клавишу...`

Вот с этой ошибкой боролся так:

`(venv) root@severcart-linux:/var/venv# pip install lxml
Collecting lxml
  Using cached lxml-3.6.4-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: lxml
Successfully installed lxml-3.6.4`

Далее отредактировал строку 146 в файле severcart-master\severcart-master\tkinstaller\install.py:

`['lxml==%s.%s.%s' % (sys.version_info.major, sys.version_info.minor, sys.version_info.micro)],`
на это
`['lxml==3.4.4'],`

Затем установка приобретает вот такой оборот:

`(venv) root@severcart-linux:/var/venv# python3 /var/venv/severcart/tkinstaller/install.py
Enter the language code [en|ru]: ru
-------------------------------------------------
--------Установка пакетов зависимостей-----------
-------------------------------------------------
Установка пакетов зависимостей для Linux
10%
20%
30%
40%
50%
60%
70%
80%
100%
-------------------------------------------------
--Генерация ключа подписи сессионной переменной--
-------------------------------------------------
Выполнено.
Traceback (most recent call last):
  File "/var/venv/severcart/tkinstaller/install.py", line 188, in <module>
    django.setup()
  File "/var/venv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/venv/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/var/venv/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/var/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'pytz'`

Ну тут все тоже было просто

`(venv) root@severcart-linux:/var/venv# pip install pytz
Collecting pytz
  Using cached pytz-2016.7-py2.py3-none-any.whl
Installing collected packages: pytz
Successfully installed pytz-2016.7`

В итоге установка прошла на ура:

`(venv) root@severcart-linux:/var/venv# python3 /var/venv/severcart/tkinstaller/install.py
Enter the language code [en|ru]: ru
-------------------------------------------------
--------Установка пакетов зависимостей-----------
-------------------------------------------------
Установка пакетов зависимостей для Linux
10%
20%
30%
40%
50%
60%
70%
80%
100%
-------------------------------------------------
--Генерация ключа подписи сессионной переменной--
-------------------------------------------------
Выполнено.
-------------------------------------------------
-----------------Миграция схемы------------------
-------------------------------------------------
Migrations for 'index':
  0009_auto_20161018_1822.py:
    - Change managers on organizationunits
Operations to perform:
  Apply all migrations: docs, sessions, index, accounts, contenttypes, storages, events, service, auth
Running migrations:
  Rendering model states... DONE
  Applying index.0001_initial... OK
  Applying accounts.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying docs.0001_initial... OK
  Applying events.0001_initial... OK
  Applying events.0002_auto_20160829_1526... OK
  Applying index.0002_auto_20160717_0859... OK
  Applying index.0003_auto_20160829_1149... OK
  Applying index.0004_remove_cartridgeitem_cart_number_postfix... OK
  Applying index.0005_auto_20161008_2114... OK
  Applying index.0007_cartridgeitem_vote... OK
  Applying index.0008_auto_20161010_1116... OK
  Applying index.0009_auto_20161018_1822... OK
  Applying service.0001_initial... OK
  Applying service.0002_auto_20160830_1129... OK
  Applying service.0003_auto_20160830_1217... OK
  Applying service.0004_settings_print_name_ou... OK
  Applying service.0005_auto_20161008_1519... OK
  Applying sessions.0001_initial... OK
  Applying storages.0001_initial... OK
Схема успешно мигрирована.
-------------------------------------------------
--------------Создание пользователя--------------
-------------------------------------------------
Ввведите имя пользователя: admin
Введите пароль:   admin
Повторите пароль: admin
Пользователь успешно создан.
-------------------------------------------------
----------Установка успешно завершена------------
-------------------------------------------------`

Далее запустил апач, залогинился, поковырял справочники, добавил пару картриджей, провел с ними полный цикл в программе, в общем норм. Но сразу скажу что возникла ошибка с сохранением настроек системы. где указывается часовой пояс.
Вот вывод debug.log:

`ERROR 2016-10-18 18:50:28,144 [/var/venv/lib/python3.5/site-packages/django/core/handlers/base.py:284] Internal Server Error: /service/general_settings/
Traceback (most recent call last):
  File "/var/venv/severcart/service/helpers.py", line 48, in commit
    self.m1 = Settings.objects.get(pk=1)
  File "/var/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/venv/lib/python3.5/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
service.models.DoesNotExist: Settings matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/venv/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/venv/severcart/common/helpers.py", line 87, in wrapper
    return view_method(request, *args, **kwargs)
  File "/var/venv/severcart/service/views.py", line 66, in general_settings
    conf.commit()
  File "/var/venv/severcart/service/helpers.py", line 63, in commit
    time_zone      = self.m1.time_zone,
AttributeError: 'SevercartConfigs' object has no attribute 'm1'`


Далее, попробовал накатить дамп БД с рабочего сервера на Windows. при экспорте кстати сразу выставляю кодировку UTF8.
После операции замещения базы войти в систему уже не удалось. 
На странице вижу вот такой текст
Ошибка 404! Страница не найдена.
Справка
Ошибка на стороне сервера!
И вывод лога debug.log:

`ERROR 2016-10-18 19:50:45,765 [/var/venv/lib/python3.5/site-packages/django/core/handlers/base.py:284] Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/var/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "accounts_anconuser" does not exist
LINE 1: ..."."email", "accounts_anconuser"."secret_key" FROM "accounts_...



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/venv/severcart/accounts/views.py", line 43, in login
    user = authenticate(username=request.POST['username'], password=request.POST['password'])
  File "/var/venv/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/var/venv/severcart/accounts/backends.py", line 16, in authenticate
    user = AnconUser.objects.get(username=username)
  File "/var/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/venv/lib/python3.5/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/var/venv/lib/python3.5/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/var/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/var/venv/lib/python3.5/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/var/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "/var/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/venv/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "accounts_anconuser" does not exist
LINE 1: ..."."email", "accounts_anconuser"."secret_key" FROM "accounts_...
`
Вот собственно и всё.

**Comment by sem174** [comment]
Вопрос с обновлением так и остаётся открытым. Увы не все же разработчики и программисты, например мне с моим уровнем познаний без рабочей инструкции не обновиться (

**Comment by sfcl** [comment]
Подготовил инструкцию на вики http://wiki.severcart.org/doku.php/development/install_master_branch.
Сегодня по ней девелоперскую конфигурацию поднял.

**Comment by sem174** [comment]
Ну это ладно, но как быть с продакшн ?
Вы поднимаете конфигурацию с нуля. А как быть с обновлением ? Оно то не работает (.
У меня есть рабочая версия, у вы на Windows. Вы же сами ответили что Windows будет "потрачен" в будущем. Установить с чистого листа на Ubuntu удается, снять дамб бд и залить его на новый сервер, а вот обновить не получается. Ну работать на версии с ошибками тоже как то не очень, а они есть.

**Comment by sfcl** [comment]
Master ветка не является готовой к продакшен. Перед выпуском нового релиза производится тестирование и исправление багов, поэтому предлагаю подождать стабильный релиз программы.

**Comment by sem174** [comment]
Ок, это ясно.
Кстати не знаю с чем может быть связано, но попробовал поставить 64 разрядную версию Ubuntu сервера и на него перетащить рабочую копию с Windows. Работает, потом накатил последний срез master, выполнил makemirations и migrate, всё прошло и заработало.
Делал Всё по тем же инструкциям. Вероятно есть проблемы с установкой на 32 битную систему.
Так понимаю что топик можно закрывать.
