### ISSUE TITLE
Акт приёма и передачи картриджей

### ISSUE THREAD

**Issue by sem174** [sfcl/severcart#108]
Акт на передачу картриджей имеется, а на приём ?
Бывает такое:
В заправку передаются 30 различных картриджей.
Из заправки обратно привозят только 25 с объяснением что на остальные 5 нет чипов\валов\тонера и они будут заправлены и доставлены позже.
Ну и хотелось бы сразу же принять все что привезли по штрих кодам и тут же распечатать акт приёма только на то что привезли обратно.
Скажем так, что дополнительный акт передачи от заправщика с подписью, в котором видно что привезено не всё, это дополнительная страховка организации от недобросовестного сервиса по заправке.

**Comment by sfcl** [comment]
На возврат не генерируется.  Это упущение.

**Comment by sem174** [comment]
Хм...
Есть косяк с актом приема картриджа из заправки.
Графа передал - выводит имя текущего пользователя в системе.
А принял пустая.
Хотя по идее надо наоборот. Так будет правильнее.
И вообще есть ли возможность выводить в актах название контрагента. То бишь при передаче кому передаём, а при приеме от кого принимаем ?
