### ISSUE TITLE
Возврат картриджей из заправки по ШтрихСканеру

### ISSUE THREAD

**Issue by sem174** [sfcl/severcart#109]
На Ubuntu не работает возврат картриджей из заправки по штрихкодам. Пробовал как на релизе 4.0 так и на сегодняшнем срезе master.
На странице from_firm_to_stock_with_barcode при сканировании штрих кода выкидывает обратно на страницу at_work. При переходе обратно на страницу from_firm_to_stock_with_barcode область с уже отсканированными картриджами не появляется. Хотя аналогично на сервере под Windows список картриджей наполняется при сканировании, хоть и выкидывает обратно на страницу at_work.
Вопрос, это только у меня так или же есть проблемы в релизе под Linux.

**Comment by sfcl** [comment]
Пофиксил, но не проверил, т.к. разные сканеры себя по разному ведут.

**Comment by sem174** [comment]
Благодарю. теперь возврат работает. Конечно тестировал всего на паре картриджей но хоть теперь можно делать полноценный возврат.
Кстати у нас сканер Honeywell MS9520
