### ISSUE TITLE
Наклейки

### ISSUE THREAD

**Issue by sfcl** [sfcl/severcart#110]
Нужна возможность выборочной печати штрих-кодов после очистки сессии.
Выбрал галочкой картриджи в любой вкладке, какие нужно - нажал сформировать PDF и распечатал.

Во время заправки при восстановлении картриджа (по документам) могут заменить корпус, или содрать

штрих-код, нужно заменить, а сессия очищена и нет возможности распечатать. Если все сессии сохранять

в PDF при основной печати и распечатывать вместе с остальными - такой расход самоклейки никого не

устраивает.

**Comment by sem174** [comment]
А мы генерируем наклейки штрих кода (EAN13) через стороннее приложение. Если наклейка по каким то причинам отсутствует, можно просто заменить номер расходника, или удалить его и добавить заново с новым номером.
