### ISSUE TITLE
Пакетная передача РМ на заправку и склад по штрихсканеру

### ISSUE THREAD

**Issue by sem174** [sfcl/severcart#111]
При передаче РМ на заправку и передаче с заправки на склад по штрихсканеру, возникают сложности в юзабилити системы. При одновременно большом количестве картриджей, например более 20 шт., приходится вручную поджимать галочки в колонке "Что передаём". Это неудобно. Прошу Вас добавить контрольный чекбокс выделить все/снять все отметки.

**Comment by sfcl** [comment]
Добавил измнения в код.
