### ISSUE TITLE
Изменение номера РМ по штрихсканеру.

### ISSUE THREAD

**Issue by sem174** [sfcl/severcart#112]
Возможно ли сделать поддержку штрихсканеру при изменении номера РМ. При попытке изменить номер РМ, в поле когда нужно ввести новый номер, сканируем новый штрихкод который желаем присвоить для РМ. В момент сканирования окно изменения номера закрывается, новый отсканированный номер не сохраняется. Уточню что использую отдельный генератор номеров штрихкодов, и уже в данном случае на РМ клеим готовые наклейки.

**Comment by sfcl** [comment]
пофиксил.

**Comment by sem174** [comment]
Спасибо, проверил с моим сканером, работает.
