### ISSUE TITLE
Динамический поиск

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#122]
Добрый день.
Реализуйте пожалуйста динамический поиск картриджей, начиная с первой цифры что бы уже шёл поиск.
Например у меня сложный номер картриджа, состоящий из двух номеров со стикеров заправщиков через тире, и что бы найти его нужно ввести полностью весь номер картриджа. :(
Думаю это будет полезно не только мне.

**Comment by sfcl** [comment]
Уже реализовано. Возможность будет представлена в релизе 0.7.X
