### ISSUE TITLE
Структура подразделение и отчеты

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#123]
У нас в организации несколько корпусов по городу.
В разных корпусах могут быть отделы с одинаковыми названиями. Нужен, отчет показывающий какое подразделение (отдел) сколько раз и какие заправили картриджи с иерархией местоположения. А сейчас, просто список всех отделов даже если там не было заправок.
И не понятно к какому корпусу этот отдел относится. Не создавал отдельные корпуса в дереве, так как отчет нужен общий по организации.
Надеюсь понятно объяснил.

**Comment by sfcl** [comment]
Уже реализовано. Возможность будет представлена в релизе 0.7.X
