### ISSUE TITLE
Повторная отправка картриджа на ремонт

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#124]
Есть еще один вопрос.
Как реализовать повторную отправку картриджа на ремонт.
Допустим мне пришел картридж с заправки, я его переместил на склад. Далее после проверки оказалось что он печатает с дефектом, я его отправляю и они там меняют допустим фотобарабан.
Вот тут самое интересное, если картридж повторно отправлять, то его сначала нужно поставить в отдел и вернуть и тогда засчитается вторая заправка. Этот картридж я могу обнаружить не отдавая в подразделение. Или отдать и его сразу вернут. Как реализовать данную ситуацию? И картридж отдать в ремонт с актом и не увеличивать количество заправок на подразделение?

**Comment by petrkytepov** [comment]
В новой версии появился буфер, сделайте от туда возможность отправлять картридж на повторную  ремонт-заправку. Что бы не учитывать его на подразделение.

**Comment by sfcl** [comment]
Добавил кнопку "Передать фирме" на странице "Заправленные". Передача аналогична пустым. Счётчик перезаправок инкрементируется только если выбрана галочка "Заправка и очистка".
