### ISSUE TITLE
Работы производимые с картриджем

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#126]
Добрый день.
Есть вопрос по табличке в которой отмечаем что сделали с картриджем после ремонта.
- Регенерация картриджа, это общее понятие ремонта. Говорить о том, что в картридже были сделаны замены деталей и он в рабочем состоянии. Разве не так? Думаю этот пункт нужно вообще убрать.
- Добавить в табличку пункты: 1. Замена Ролика заряда 2. Замена Дозирующего лезвия

**Comment by sfcl** [comment]
Согласен, просто слово "Регенерация" можно заменить на "Засыпка тонера".

**Comment by petrkytepov** [comment]
Но это и есть заправка, не?
