### ISSUE TITLE
Backup базы

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#127]
Может не по теме.
Очень полезно делать  backup базы.
Я не специалист по ubunte, хотелось бы узнать вариант реализации резервного копирования. Было бы удобно это делать из программы, нажать кнопку backup и скачать его на комп. (допустим во вкладке Обслуживание) и там же развернуть существующий.
Или какими еще средствами можно реализовать автоматический бекап по расписанию, что бы он кидался на другой комп в сети?

**Comment by sfcl** [comment]
Бекапить исходники программы смысла нет - интерес представляет база данных. Все данные и документы хранятся там. Горячий бэкап postgresql выполняется [pg_dumpall](https://postgrespro.ru/docs/postgrespro/9.5/app-pg-dumpall.html), выполнение программы можно прописать в cron и запускать по расписанию. Возможен и холодный бэкап базы, но нужно её останавливать.

Этот способ резервирования кроссдиструбутивный, можно запускать и в CentOS, FreeBSB, Debian, ...
Реализовывать бэкап через саму программу пока не планирую. Это требует исследований и проверок.

**Comment by sfcl** [comment]
http://wiki.severcart.org/doku.php/ru/%D1%80%D0%B5%D0%B7%D0%B5%D1%80%D0%B2%D0%BD%D0%BE%D0%B5_%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%B8_%D0%B2%D0%BEc%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_ubuntu
