### ISSUE TITLE
Птичка при передаче картриджа

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#129]
Подниму заново данный вопрос, если по умолчанию стоит птичка возможны случайные возвраты, которые не нужны.
Уже несколько раз попались на этом, пока каждому инженеру по 20 раз не сказал следить за этим.
Может убрать по умолчанию?

**Comment by sem174** [comment]
Файл index/templates/index/get_cart_ou.html
Удаляем в файле записи об активности чекбоксов по умолчанию - checked="checked"
Как бы все, при обновлении процедуру повторяем.

**Comment by sfcl** [comment]
Теперь этот параметр можно настроить в Обслуживание / Настройки / Интерфейс
