### ISSUE TITLE
Не видно название и номер картриджа в pdf

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#132]
После формирования документа pdf для печати наклеек, не видно название и номер картриджа в pdf
окошко срезает.

**Comment by sfcl** [comment]
Свой файл PDF с наклейками прикрепите.

**Comment by petrkytepov** [comment]
[1483015142_1.pdf](https://github.com/sfcl/severcart/files/677077/1483015142_1.pdf)

**Comment by petrkytepov** [comment]
Samsung не влезает и если свои более длинные вносить.
