### ISSUE TITLE
Формирование отчетов для инженера

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#138]
Добрый день.
Чем отличаются права Администратора от пользователя. В пользователе не могу сформировать отчет, хотя я бы это поручил инженеру.
Можно ли это реализовать?

**Comment by sfcl** [comment]
Админ имеет доступ к работе с пользователями, редактирование организационных подразделений, настройка почты, настройки интерфейса, склады, контрагенты. Программно это регулируется через декоратор @is_admin.
Реализовать можно, только для этого нужно капитально перекопать всё приложение, реализовав матрицу доступа. Времени на это у меня пока нет.
