### ISSUE TITLE
Дублирование количества картриджей в одинаковых подразделениях

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#146]
У нас  много корпуса по городу разбросаны, есть в нескольких кабинеты (Приемная директора)
Я создал дерево и в нем ветви например:
Главный корпус - Приемная директора
Второй корпус - Приемная директора
Номера у этих подразделений разные (Организационные подразделения)
Теперь в отчете (Пользователь) у меня во всех приемных директора одинаковое ко-во картриджей!
Как так?

**Comment by petrkytepov** [comment]
Название должно быть уникальным?

**Comment by sfcl** [comment]
Скриншоты, или точную структуру на почту info@severcart.org скинь.

**Comment by sfcl** [comment]
Подмени 2а файла
        modified:   reports/api/views.py
        modified:   reports/templates/reports/users_ajax.html
из репозитория.

**Comment by petrkytepov** [comment]
Заменил, теперь выдает ошибку сервера. :(  02.02.2017, 21:16, "Maxim Hozyainov" <notifications@github.com>:Подмени 2а файлаmodified: reports/api/views.pymodified: reports/templates/reports/users_ajax.htmlиз репозитория.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- Кутепов Петр ВикторовичНачальник ОВТ, Астраханский государственный архитектурно-строительный университет. Блог мастера - http://kapten.ruЖенский портал - http://uzuri.ruЭнергоаудит - http://energoaudit30.ruСказки народов мира - http://bellastoria.ru
