### ISSUE TITLE
Не работает обновление до версии 0.8.0

### ISSUE THREAD

**Issue by sem174** [sfcl/severcart#149]
Решил обновиться с релиза 0.7.6 до 0.8.0. В итоге вижу вот такой вывод:

```
Enter the language code [en|ru]: ru
-------------------------------------------------
-------------Обновление пакетов---------
-------------------------------------------------
Установка пакетов зависимостей для Linux
10%
20%
30%
40%
50%
60%
70%
80%
100%
-------------------------------------------------
-----------------Миграция схемы------------------
-------------------------------------------------
SystemCheckError: System check identified some issues:

ERRORS:
?: debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE_CLASSES.
        HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE_CLASSES.
(venv) root@vs-severcart:/home/olegas# python3 /var/venv/severcart/tkinstaller/update.py
```

Все как всегда по инструкции, хм. что я делаю не так ?

**Comment by sfcl** [comment]
подождите официального релиза на сайте.

**Comment by petrkytepov** [comment]
Добрый день. Есть примерная дата выхода релиза?

**Comment by sfcl** [comment]
Попробуйте обновиться по инструкции до 0.8.2

**Comment by petrkytepov** [comment]
Обновление до 8,2 не получается обновить схему.
https://yadi.sk/i/zci1KCeg3E3muA

**Comment by sfcl** [comment]
Замените файл
/var/venv/severcart/conf/settings_prod.py
на
 https://raw.githubusercontent.com/sfcl/severcart/master/conf/settings_prod.py
и запустиnt update.py.

**Comment by petrkytepov** [comment]
Теперь выдает другую ошибку
https://yadi.sk/i/jA5gg9BS3E4b5m

**Comment by sfcl** [comment]
Запостил релиз 0.8.4. Перед обновлением очистите каталог от содержимого /var/venv/severcart/, /var/venv/severcart_bak/ - должен быть. Далее по инструкции. Если не помогло,
то выполняем миграцию в ручном режиме для этого:

```
source /var/venv/bin/activate
cd /var/venv/severcart/
python3 manage.py migrate
```

или 

```
python3 manage.py makemigrations --merge
python3 manage.py migrate
```

**Comment by sfcl** [comment]
Получилось обновиться? Или пришлось делать дамп базы данных и заново всё переустанавливать?

**Comment by petrkytepov** [comment]
Обновился без проблем! Спасибо.
