### ISSUE TITLE
При формировании отчета по пользователям в конце подразделения выводится Х1, Х2 или Х3

### ISSUE THREAD

**Issue by petrkytepov** [sfcl/severcart#157]
При формировании отчета по пользователям в конце подразделения выводится Х1, Х2 или Х3
Это количество картриджей, как убрать?

**Comment by sfcl** [comment]
Открываем файл reports/templates/reports/users_ajax.html в текстовом редакторе поддерживающем юникод, удаляем подстроку "X {{value.count}}" в строке № 9. Сохраняем изменения. Перезагружаем апачи.

**Comment by petrkytepov** [comment]
Спасибо, убрал.
