### ISSUE TITLE
Неоднозначная работа с пользователем

### ISSUE THREAD

**Issue by mmxbow** [sfcl/severcart#86]
При установке создал пользователя admin. 
При настройке создавал под этим пользователем организационную структуру, пользователей, типы расходных материалом и т.п.
Однако при создании склада система ругнулась - пользователь не принадлежит ни одной организации. имхо, не совсем логично.
![2016-08-15 14 11 08](https://cloud.githubusercontent.com/assets/16224296/17663413/6c0eb834-62fd-11e6-8b0e-cd06d6aefe11.png)

**Comment by sfcl** [comment]
Всё логично. Пользователь не ассоциирован с организацией.  Делается через Справочники / Управление пользователями, далее выбираете пользователя и нажимаете кнопку "Редактировать".  Затем связываете его с организацией (корневой) и сохраняете. После этого можно склады и картриджи создавать.
