### ISSUE TITLE
FR: учёт расходников по штрих-коду

### ISSUE THREAD

**Issue by mmxbow** [sfcl/severcart#88]
Feature Request:
Нет планов по использованию ШК для учёта движения расходных материало (РМ)?
Как мне видится, ШК можно использовать для идентификации конкретного экземпляра РМ, а также ШК производителя при регистрации нового экземпляра РМ (выбор типа/наименования РМ).
Ещё я тут накидал несколько схем процессов, которые несколько упрощенно используются у меня на работе, возможно, пригодится :
![2](https://cloud.githubusercontent.com/assets/16224296/17698925/e04162de-63ce-11e6-9794-ea63b91faac6.jpg)

**Comment by sfcl** [comment]
> Нет планов по использованию ШК для учёта движения расходных материало (РМ)?

Планы такие есть. Но техническая реализация данной идеи, как мне видится, решаема двумя путями. Первый. Переписать приложение заново, например на Delphi приспособив к нему интерфейс по взаимодействию с сканером ШК (опрашивая устройство в бесконечном цикле, либо выполняя запуск подпрограммы обработчика события сканирования). От web интерфейса придётся отказаться как от рудимента, а это большой минус (пострадает многоплатформенность приложения ). Второй. Разработать приложение агент, на том же Delphi/C++, которое будет запускаться в режиме службы ожидая поступления события от сканера ШК. Далее данные о РМ отправляя на web сервер, через REST API. Оба варианты осуществимы, но запрограммировать подобное трудозатратно. Если реализовать данные замыслы, то удобство работы с приложением будет очень высоким, например проведя через сканер РМ на дисплее отобразится вся служебная информация с возможными действиями на объектом.

>Как мне видится, ШК можно использовать для идентификации конкретного экземпляра РМ, а также ШК производителя при регистрации нового экземпляра РМ (выбор типа/наименования РМ).

Какую информацию в себе содержит ШК? Уникальный номер, код призводителя, код товара, ... Причём у каждого производителя свой формат, и своя служебная информация. Причём по опыту скажу, что не на всех РМ производитель наносит штрихкоды.

Если программа будет печатать наклейки с штрихкодами, то выгоды большой я не вижу, с таким же успехом можно пользоваться просто наклейками с уникальными, человеко читаемыми номерами.

Я думаю, что небольшая организация или фирма не будет закупать под эти нужды специальные сканеры и принтеры для ШК. 

Схемы процессов примерно соответствуют программной реализации. Отличия на мой взгляд в терминологии.  Было бы не плохо если были бы предложения с вариантами пользовательского интерфейса и шаблонами документов.
