### ISSUE TITLE
Не могу становить на Gentoo

### ISSUE THREAD

**Issue by xlin** [sfcl/severcart#96]
Все сделано по инструкции. Зависимости установил. Но в логах апача выпадет
http://pastebin.com/MHuQJTi8

Получаю 500 Internal Server Error

**Comment by sfcl** [comment]
Инструкция увы не пригодна для Gentoo. Судя по логам не создалось виртуального окружения для Python пакетов, программа подключает модули с каталога /usr/lib64/python2.7/site-packages/, хотя должна с каталога /var/venv/Lib/site-packages. Severcart работает только с Python 3.x в логах он 2.7. 

За символическую сумму готов подготовить инструкции по установке программы на Gentoo.

**Comment by xlin** [comment]
Смысл было тогда программу выкладывать с GPL лицензией? Спасибо. Буду разбираться сам.

**Comment by sfcl** [comment]
Смысл выкладывать программу под лицензией GPL есть. 1 - Траст. Каждый кто умеет читать код может удостовериться, что в программе нет закладок и троянов. 2 - Она проста как 5 копеек, поэтому прятать исходники незачем. 3 - Маркетинг. 4 - Любой может принять участие в разработке программы, Пул Реквесты принимаются, и возможно будут смерженны с мастер веткой. 5 - Лицензия GPL не запрещает продавать тех. поддержку за деньги.

**Comment by xlin** [comment]
Это все понятно. Просто обычно разработчики помогаю, дабы продвинуть свой проект в массы. Один поставил, похвастался другу. Тот тоже влепил и т.д. Проходит время и у проекта появляется монетизация. Но Вы с этим можете не соглашаться. Это мое ИМХО.

Добавил строку PYTHON_SINGLE_TARGET="python3_4" в make.conf и выполнил emerge -uDN @world

В итоге WSGI мобрался с третий питоном т проект стартанул. Зависимости ставятся из списка приведенного в исходниках. Всех благ.
